# KEYS #
game_id = 'gameid'
url = 'url'
league = 'league'
split = 'split'
date = 'date'
week = 'week'
game = 'game'
patch_no = 'patchno'
player_id = 'playerid'

side = 'side'
position = 'position'
player = 'player'
team = 'team'
champion = 'champion'
ban1 = 'ban1'
ban2 = 'ban2'
ban3 = 'ban3'
ban4 = 'ban4'
ban5 = 'ban5'
game_length = 'gamelength'
result = 'result'

kills = 'k'
deaths = 'd'
assists = 'a'
team_kills = 'teamkills'
team_deaths = 'teamdeaths'
doubles = 'doubles'
triples = 'triples'
quadras = 'quadras'
pentas = 'pentas'
first_blood = 'fb'
first_blood_assist = 'fbassist'
first_blood_victim = 'fbvictim'
kills_per_min = 'kpm'
opp_kill_per_min = 'okpm'
game_kill_per_min = 'ckpm'

first_dragon = 'fd'
first_dragon_time = 'fdtime'
team_drag_kills = 'teamdragkills'
opp_drag_kills = 'oppdragkills'
elemental_drags = 'elementals'
opp_elemental_drags = 'oppelementals'
fire_drakes = 'firedrakes'
water_drakes = 'waterdrakes'
earth_drakes = 'earthdrakes'
air_drakes = 'airdrakes'
elder_drakes = 'elders'
opp_elder_drakes = 'oppelders'

herald = 'herald'
herald_time = 'herald'

first_tower = 'ft'
first_tower_time = 'fttime'
first_mid_outer = 'firstmidouter'
first_three_towers = 'firsttothreetowers'
team_tower_kills = 'teamtowerkills'
opp_tower_kills = 'opptowerkills'

first_baron = 'fbaron'
first_baron_time = 'fbarontime'
team_baron_kills = 'teambaronkills'
opp_baron_kills = 'oppbaronkills'

dmg_to_champs = 'dmgtochamps'
dmg_to_champs_per_min = 'dmgtochampspermin'
dmg_share = 'dmgshare'

wards = 'wards'
wards_per_min = 'wardspermin'
ward_share = 'wardshare'
ward_kills = 'wardkills'
wcpm = 'wcpm' # TODO: Ask Tim what this is
vision_wards = 'visionwards'
vision_ward_buys = 'visionwardbuys'
visible_ward_clear_rate = 'visiblewardclearrate'
invisible_ward_clear_rate = 'invisiblewardclearrate'

total_gold = 'totalgold'
earned_gold_share = 'earnedgoldshare'
earned_gold_per_min = 'earnedgpm'
gold_spent = 'goldspent'
gspd = 'gspd' # TODO: Ask Tim what this is
gold_at_10 = 'goldat10'
opp_gold_at_10 = 'oppgoldat10'
gd_at_10 = 'gdat10'
gold_at_15 = 'goldat15'
opp_gold_at_15 = 'oppgoldat15'
gd_at_15 = 'gdat15'

xp_at_10 = 'xpat10'
opp_xp_at_10 = 'oppxpat10'

minion_kills = 'minionkills'
monster_kills = 'monsterkills'
monster_kills_own_jng = 'monsterkillsownjungle'
monster_kills_opp_jng = 'monsterkillsenemyjungle'

cs_per_min = 'cspm'
cs_at_10 = 'csat10'
opp_cs_at_10 = 'oppcsat10'
csd_at_10 = 'csdat10'
cs_at_15 = 'csat15'
opp_cs_at_15 = 'oppcsat15'
csd_at_15 = 'csdat15'


# TEAMS #
AHQ = 'AHQ e-Sports Club'
CG = 'Clutch Gaming'
C9 = 'Cloud9'
DFM = 'DetonatioN FocusMe'
DMW = 'Damwon Gaming'
FLA = 'Flamengo'
FNC = 'Fnatic'
FPX = 'Funplus Phoenix'
GAM = 'GAM Esports'
GRF = 'Griffin'
G2 = 'G2 Esports'
HKA = 'Hong Kong Attitude'
IG = 'Invictus Gaming'
ISG = 'Isurus Gaming'
JT = 'J Team'
LK = 'Lowkey Esports'
MG = 'MEGA Esports'
MMM = 'Mammoth'
SKT = 'SK Telecom T1'
SPY = 'Splyce'
RNG = 'Royal Never Give Up'
RYL = 'Royal Youth'
TL = 'Team Liquid'
UOL = 'Unicorns of Love'
